### ISSUE TITLE
Modal - Regression from 2.0.0-rc.19 to 2.0.0-rc.20

### ISSUE THREAD

**Issue by bpolaszek** [bootstrap-vue/bootstrap-vue#3353]
Hey there!

I've got a strange bug when upgrading from 2.0.0-rc.19 to 2.0.0-rc.20.

Consider the following component:
```vue
<template>
    <bootstrap-modal ref="modal">
        <form>

            <input type="text" class="form-control">

        </form>

    </bootstrap-modal>
</template>
<script>

    import BootstrapModal from 'bootstrap-vue/es/components/modal/modal';

    export default {
        components: {
            BootstrapModal,
        },
        methods: {
            show() {
                this.$refs.modal.show();
            },
            hide() {
                this.$refs.modal.hide();
            },
        },
        mounted() {
            this.show();
            console.log(this.$el.querySelector('form'));
            console.log(this.$el);
        }
    }
</script>
```

#### On 2.0.0-rc.19

* The modal is properly shown when the component is mounted
* First `console.log` outputs a `<form></form>` element
* Second `console.log` outputs a `<div></div>` element with nested divs in it

#### On 2.0.0-rc.20

* The modal is properly shown when the component is mounted
* First `console.log` throws a `TypeError: this.$el.querySelector is not a function`
* Second `console.log` outputs `<!-- -->` 

Maybe it's related to #3312?

Thank you!
Ben

**Comment by jackmu95** [comment]
@bpolaszek Yeah it is related to #3312.
When you wan't the old behavior (rendering the modal when it isn't visible) make sure to use the `static` prop.

**Comment by bpolaszek** [comment]
Hello @jackmu95,

Thank you for your quick answer. It works fine now!
Sorry for disturbing.

Have a nice day!
Ben
